Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -30,25 +30,36 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Maximize build space
-        uses: easimon/maximize-build-space@master
-        with:
-          root-reserve-mb: 8192
-          temp-reserve-mb: 2048
-          swap-size-mb: 8192
-          remove-dotnet: 'true'
-          remove-android: 'true'
-          remove-haskell: 'true'
-          remove-codeql: 'true'
+       - name: Checkout Code
+         uses: actions/checkout@v4
+         with:
+          fetch-depth: 1
 
-      - name: Install Repo and Python
-        run: |
-          # Install dependencies
-          sudo apt update
-          sudo apt install repo python3 python-is-python3
+       - name: Free Disk Space
+         run: |
+          sudo apt-get update -qq
+          sudo apt-get install -qq curl
+          curl -fsSL https://raw.githubusercontent.com/kou/arrow/e49d8ae15583ceff03237571569099a6ad62be32/ci/scripts/util_free_space.sh | bash
+       - name: Setup Build Environment
+         run: |
+          sudo apt-get update
+          sudo apt-get install -y --no-install-recommends \
+            python3-pip curl git zip unzip gcc g++ make ninja-build file \
+            bc bison flex libssl-dev libelf-dev wget build-essential \
+            python3-dev python3-setuptools rsync ccache cmake libdw-dev zlib1g-dev     
+       - name: Setup Python and Repo Tool
+         run: |
+          python3 -m pip install --upgrade pip
+          pip3 install gitpython xmltodict
+          mkdir -p ~/.bin
+          curl -s https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
+          chmod a+x ~/.bin/repo
+          echo "$HOME/.bin" >> $GITHUB_PATH
+          git config --global user.name "GitHub Actions Bot"
+          git config --global user.email "actions@github.com"
 
-      - name: Set CONFIG Environment Variable
-        run: |
+       - name: Set CONFIG Environment Variable
+         run: |
           CONFIG="${{ inputs.model }}"
           
           # Set CONFIG as an environment variable for future steps
@@ -56,8 +67,8 @@ jobs:
           
           echo "CONFIG set to: $CONFIG"
 
-      - name: Clone AnyKernel3 and Other Dependencies
-        run: |
+       - name: Clone AnyKernel3 and Other Dependencies
+         run: |
           echo "Cloning AnyKernel3 and other dependencies..."
           
           ANYKERNEL_BRANCH="gki-2.0"
@@ -72,8 +83,8 @@ jobs:
           git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "$SUSFS_BRANCH"
           git clone https://github.com/TheWildJames/kernel_patches.git
 
-      - name: Initialize and Sync Kernel Source
-        run: |
+       - name: Initialize and Sync Kernel Source
+         run: |
           echo "Creating folder for configuration: $CONFIG..."
           mkdir -p "$CONFIG"
           cd "$CONFIG"
@@ -86,8 +97,8 @@ jobs:
           repo --version
           repo --trace sync -c -j$(nproc --all) --no-tags --fail-fast
       
-      - name: Add KernelSU
-        run: |
+       - name: Add KernelSU
+         run: |
           echo "Changing to configuration directory: $CONFIG..."
           cd "$CONFIG/kernel_platform"
           
@@ -99,8 +110,8 @@ jobs:
           echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
           sed -i "s/DKSU_VERSION=11998/DKSU_VERSION=${KSU_VERSION}/" Makefile
 
-      - name: Apply SUSFS Patches
-        run: |
+       - name: Apply SUSFS Patches
+         run: |
           echo "Changing to configuration directory: $CONFIG..."
           cd "$CONFIG/kernel_platform"
           
@@ -124,24 +135,24 @@ jobs:
           fi
           patch -p1 < 50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch || true
 
-      - name: Apply KSU Hooks
-        run: |
+       - name: Apply KSU Hooks
+         run: |
           echo "Changing to configuration directory: $CONFIG..."
           cd "$CONFIG/kernel_platform/common"
           # Apply additional patch
           cp ../../../kernel_patches/next/next_hooks.patch ./
           patch -p1 --fuzz=3 < ./next_hooks.patch
           
-      - name: Apply Hide Stuff Patches
-        run: |
+       - name: Apply Hide Stuff Patches
+         run: |
           echo "Changing to configuration directory: $CONFIG..."
           cd "$CONFIG/kernel_platform/common"
           # Apply additional patch
           cp ../../../kernel_patches/69_hide_stuff.patch ./
           patch -p1 -F 3 < 69_hide_stuff.patch
 
-      - name: Add SUSFS Configuration Settings
-        run: |
+       - name: Add SUSFS Configuration Settings
+         run: |
           echo "Changing to configuration directory: $CONFIG..."
           cd "$CONFIG/kernel_platform"
           
@@ -195,8 +206,8 @@ jobs:
             echo "CONFIG_DYNAMIC_DEBUG=n" ./common/arch/arm64/configs/gki_defconfig
             echo "CONFIG_DEBUG_INFO=n" ./common/arch/arm64/configs/gki_defconfig
 
-      - name: Run sed and perl Commands
-        run: |
+       - name: Run sed and perl Commands
+         run: |
           echo "Changing to configuration directory: $CONFIG..."
           cd "$CONFIG/kernel_platform"
           
@@ -209,36 +220,32 @@ jobs:
           sed -i 's/-dirty//' ./external/dtc/scripts/setlocalversion
           sed -i 's/-dirty//' ./build/kernel/kleaf/workspace_status_stamp.py || echo "No workspace_status_stamp.py!"                
 
-      - name: Build the Kernel
-        run: |
+       - name: Build the Kernel
+         run: |
           echo "Changing to configuration directory: $CONFIG..."
           cd "$CONFIG"
           
-          echo "Building the kernel..."
-          rm ./kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
-          rm ./kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"          
-          
-          BUILD_TYPE="gki"
-          if [ "${{ inputs.soc }}" == "sun" ]; then
-            BUILD_TYPE="perf"
-          fi          
-          sed -i '/"\${ROOT_DIR}\/build_with_bazel.py"/i EXTRA_KBUILD_ARGS+=" --jobs=4"' ./kernel_platform/msm-kernel/build_with_bazel.py
-          export MAKEFLAGS="-j$(nproc)"
-          find ./kernel_platform -type f -exec sed -i 's/\(make\s\+-C[^\n]*\)\s\+/\1 -j$(nproc) /g' {} +
-          sed -i 's/set \+-e/set -ex/g' ./kernel_platform/build/android/prepare_vendor.sh
-          sed -i '/if \[ "\${RECOMPILE_KERNEL}" == "1" \]; then/i set -x' ./kernel_platform/build/android/prepare_vendor.sh
-          LTO=thin ./kernel_platform/oplus/build/oplus_build_kernel.sh ${{ inputs.soc }} $BUILD_TYPE
-          
-      - name: Copy Images
-        run: |
+           ./build_with_bazel.py \
+               -t sun perf \
+               gki \
+               --jobs=$(nproc --all) \
+               --verbose_failures \
+               --config=stamp \
+               --user_kmi_symbol_lists=//msm-kernel:android/abi_gki_aarch64_qcom \
+               --ignore_missing_projects \
+               --lto=thin \
+               -o "$(pwd)/out" || { echo "Bazel build failed"; exit 1; }
+
+       - name: Copy Images
+         run: |
           echo "Changing to configuration directory: $CONFIG..."
           cd "$CONFIG"
 
           echo "Copying Image"
           cp ./out/dist/Image ../AnyKernel3/Image
 
-      - name: Create ZIP Files for Different Formats
-        run: |
+       - name: Create ZIP Files for Different Formats
+         run: |
           echo "Navigating to AnyKernel3 directory..."
           cd ./AnyKernel3
 
@@ -247,9 +254,9 @@ jobs:
           echo "Creating zip file $ZIP_NAME..."
           zip -r "../$ZIP_NAME" ./*
           
-      - name: Upload Build Artifacts
-        uses: actions/upload-artifact@v4
-        with:
+       - name: Upload Build Artifacts
+         uses: actions/upload-artifact@v4
+         with:
           name: kernel-${{ env.CONFIG }}
           path: |
             *.zip
